### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Piixell** [Duts/Pushbullet#3]
Your request for the new logo.
![icon128](https://cloud.githubusercontent.com/assets/11403318/6593879/aa690c32-c7dc-11e4-8bf6-9bdf35b209e9.png)
![icon16](https://cloud.githubusercontent.com/assets/11403318/6593880/aa6ae4a8-c7dc-11e4-9148-e8f8695b06de.png)
![icon32](https://cloud.githubusercontent.com/assets/11403318/6593881/aad9a24e-c7dc-11e4-9a8d-140541483a48.png)
![icon48](https://cloud.githubusercontent.com/assets/11403318/6593882/aade70ee-c7dc-11e4-91f1-1aa4ba741758.png)
![icon64](https://cloud.githubusercontent.com/assets/11403318/6593883/aae1ede6-c7dc-11e4-80d2-6c22fbb8b033.png)

**Comment by Duts** [comment]
Thanks!
