### ISSUE TITLE
Licensing the project and plans for future

### ISSUE THREAD

**Issue by Abyss777** [Duts/Pushbullet#4]
Hello, Robert.

I wanted to write my own application for Pushbullet, but found yours. It is in initial state. It is need to be improved. I've made some improvements in fork https://github.com/Abyss777/Firepush but before contribute I need to know the License of your project. My suggestion is GPLv2.

If you don't have plans to develop your project I'll try to do it by my self and I need your permission to use your code.

**Comment by Duts** [comment]
Hi Andrey,
If you want we can collaborate to this application. Actually I'm testing
the 0Auth2 Login and other features, let me know something soon.

-Robert
